export const BRANDS = [
  '365',
  'Ada',
  'Al Nakhla',
  'Alpha',
  'Alwan',
  'Antique Gold Coin',
  'Bovo',
  'Burqaa',
  'Carre',
  'Colori',
  'Colour Classic',
  'Danah',
  'Danah Diamond',
  'Dancing Diamond',
  'Diana',
  'Disney Collection',
  'Dunyati',
  'Eclat',
  'Eid Collection',
  'Evara',
  'Farfalla',
  'Farfalla Diamond',
  'Floats',
  'Fortuna Diamond',
  'Frost',
  'Hoops',
  'Hoops Diamond',
  'Horoufi Diamond',
  'Horoufi Gold',
  'Ishi Biladi',
  'Jawhara Collection',
  'May Birthstones',
  'Mosaic',
  'Princess Milano',
  'Rabiya',
  'Scala',
  'Shnaf',
  'Shnaf Diamond',
  'Solitaire',
  'Tabla Diamond',
  'Tanzanite',
  'Tennis',
  'Trendy',
  'Umi Dunyati',
  'Valentine Collection',
  'Vida',
  'Worood',
];
